BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "demo"
BBFILE_PATTERN_demo = "^${LAYERDIR}/"
BBFILE_PRIORITY_demo = "6"

# Check compatibility against the actual Yocto release before use.
LAYERSERIES_COMPAT_demo = "scarthgap styhead walnascar whinlatter wrynose"
